version: 2
enable-beta-ecosystems: true
updates:
- package-ecosystem: gomod
  directory: /
  allow:
  - dependency-type: all
  schedule:
    interval: weekly
  groups:
    golang-dependencies:
      patterns:
      - github.com/golang*
    k8s-dependencies:
      patterns:
      - k8s.io*
      - sigs.k8s.io*
    github-dependencies:
      patterns:
      - github.com*
      exclude-patterns:
      - github.com/golang*
  labels:
  - area/dependency
  - release-note-none
  - ok-to-test
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - area/dependency
  - release-note-none
  - ok-to-test
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
