/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kubernetes-csi/external-provisioner/client/apis/volumepopulator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumePopulators implements VolumePopulatorInterface
type FakeVolumePopulators struct {
	Fake *FakePopulatorV1beta1
}

var volumepopulatorsResource = schema.GroupVersionResource{Group: "populator.storage.k8s.io", Version: "v1beta1", Resource: "volumepopulators"}

var volumepopulatorsKind = schema.GroupVersionKind{Group: "populator.storage.k8s.io", Version: "v1beta1", Kind: "VolumePopulator"}

// Get takes name of the volumePopulator, and returns the corresponding volumePopulator object, and an error if there is any.
func (c *FakeVolumePopulators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VolumePopulator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(volumepopulatorsResource, name), &v1beta1.VolumePopulator{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VolumePopulator), err
}

// List takes label and field selectors, and returns the list of VolumePopulators that match those selectors.
func (c *FakeVolumePopulators) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VolumePopulatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(volumepopulatorsResource, volumepopulatorsKind, opts), &v1beta1.VolumePopulatorList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.VolumePopulatorList{ListMeta: obj.(*v1beta1.VolumePopulatorList).ListMeta}
	for _, item := range obj.(*v1beta1.VolumePopulatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumePopulators.
func (c *FakeVolumePopulators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(volumepopulatorsResource, opts))
}

// Create takes the representation of a volumePopulator and creates it.  Returns the server's representation of the volumePopulator, and an error, if there is any.
func (c *FakeVolumePopulators) Create(ctx context.Context, volumePopulator *v1beta1.VolumePopulator, opts v1.CreateOptions) (result *v1beta1.VolumePopulator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(volumepopulatorsResource, volumePopulator), &v1beta1.VolumePopulator{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VolumePopulator), err
}

// Update takes the representation of a volumePopulator and updates it. Returns the server's representation of the volumePopulator, and an error, if there is any.
func (c *FakeVolumePopulators) Update(ctx context.Context, volumePopulator *v1beta1.VolumePopulator, opts v1.UpdateOptions) (result *v1beta1.VolumePopulator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(volumepopulatorsResource, volumePopulator), &v1beta1.VolumePopulator{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VolumePopulator), err
}

// Delete takes name of the volumePopulator and deletes it. Returns an error if one occurs.
func (c *FakeVolumePopulators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(volumepopulatorsResource, name), &v1beta1.VolumePopulator{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumePopulators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(volumepopulatorsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.VolumePopulatorList{})
	return err
}

// Patch applies the patch and returns the patched volumePopulator.
func (c *FakeVolumePopulators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VolumePopulator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(volumepopulatorsResource, name, pt, data, subresources...), &v1beta1.VolumePopulator{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VolumePopulator), err
}
