kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: test-csi-provisioner 
  resources:
    requests:
      storage: 1Mi
